apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluscode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pluscode
  template:
    metadata:
      labels:
        app: pluscode
    spec:
      containers:
      - name: pluscode-container
        image: wdenniss/pluscode-demo:latest
        resources:
            requests:
              cpu: 200m
              memory: 250Mi